/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BookedTime {
  'id' : bigint,
  'urgencyLevel' : string,
  'bookingId' : bigint,
  'patientComments' : string,
  'sampleCollectionTime' : bigint,
  'cateringPreference' : string,
  'timeUnix' : bigint,
}
export interface Booking {
  'id' : bigint,
  'userName' : string,
  'address' : string,
  'serviceRequest' : {
    'subcategory' : Subcategory,
    'description' : string,
    'preferredDate' : [] | [bigint],
    'preferredTime' : [] | [bigint],
    'category' : Category,
    'urgent' : boolean,
  },
  'budget' : bigint,
  'requestType' : { 'whatsapp' : { 'phoneNumber' : string } } |
    { 'callBack' : { 'requestedTime' : bigint } } |
    { 'scheduledVisit' : { 'timestamp' : bigint } },
}
export type Category = { 'specializedCare' : null } |
  { 'medicalEquipment' : null } |
  { 'preventiveCare' : null } |
  { 'primaryHealthcare' : null };
export interface ConsultationNote {
  'doctorId' : bigint,
  'diagnosticRequests' : Array<string>,
  'noteId' : bigint,
  'patientId' : bigint,
  'createdAt' : Time,
  'soapNotes' : string,
  'prescriptionFile' : string,
  'updatedAt' : Time,
  'followupDate' : Time,
  'appointmentId' : bigint,
}
export interface Customer {
  'status' : string,
  'primaryPatientId' : bigint,
  'referralCode' : string,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'customerId' : bigint,
  'phone' : string,
  'walletBalance' : number,
  'principalId' : [] | [Principal],
}
export interface DashboardStats {
  'totalOrders' : bigint,
  'pendingReports' : bigint,
  'totalPhlebotomists' : bigint,
  'completedOrders' : bigint,
  'activeOrders' : bigint,
  'totalUsers' : bigint,
}
export interface Data {
  'id' : bigint,
  'metaDescription' : string,
  'pageDescription' : string,
  'metaKeywords' : string,
  'keywords' : Array<string>,
  'metaTitle' : string,
  'canonicalUrl' : string,
  'pageTitle' : string,
}
export interface DiagnosticTest {
  'reportDeliveryTime' : string,
  'createdAt' : Time,
  'testName' : string,
  'sampleType' : string,
  'isActive' : boolean,
  'updatedAt' : Time,
  'preparationInstructions' : string,
  'category' : string,
  'searchKeywords' : Array<string>,
  'testDescription' : string,
  'price' : number,
  'testId' : bigint,
}
export interface DoctorAppointment {
  'fee' : number,
  'status' : string,
  'doctorId' : bigint,
  'patientId' : bigint,
  'createdAt' : Time,
  'notes' : string,
  'customerId' : bigint,
  'scheduledDateTime' : Time,
  'appointmentId' : bigint,
  'consultationType' : string,
}
export interface DoctorDashboardStats {
  'completedConsultations' : bigint,
  'todayAppointments' : bigint,
  'totalPatients' : bigint,
  'pendingPrescriptions' : bigint,
  'rating' : number,
  'earningsToday' : number,
}
export interface DoctorEarning {
  'doctorId' : bigint,
  'paymentStatus' : string,
  'earningId' : bigint,
  'date' : Time,
  'paymentDate' : Time,
  'amount' : number,
  'appointmentId' : bigint,
  'transactionId' : string,
}
export interface DoctorProfile {
  'status' : string,
  'doctorId' : bigint,
  'userId' : bigint,
  'createdAt' : Time,
  'profilePhoto' : string,
  'qualifications' : Array<string>,
  'experience' : bigint,
  'availability' : string,
  'specialization' : string,
  'totalConsultations' : bigint,
  'rating' : number,
  'certifications' : Array<string>,
  'consultationFee' : number,
}
export type ExternalBlob = Uint8Array;
export interface HealthPackage {
  'packageName' : string,
  'testInclusions' : Array<string>,
  'sampleCollection' : string,
  'reportDeliveryTime' : string,
  'createdAt' : Time,
  'description' : string,
  'isActive' : boolean,
  'iconName' : string,
  'updatedAt' : Time,
  'shortDescription' : string,
  'category' : string,
  'price' : number,
  'packageId' : bigint,
}
export type HealthcareRole = { 'patient' : null } |
  { 'corporateAdmin' : null } |
  { 'admin' : null } |
  { 'doctor' : null } |
  { 'franchiseAdmin' : null } |
  { 'labExecutive' : null } |
  { 'phlebotomist' : null };
export interface Info {
  'locationUrl' : string,
  'email' : string,
  'address' : string,
  'openingHours' : string,
  'phone' : string,
}
export interface Info__1 {
  'backgroundColor' : string,
  'primaryColor' : string,
  'logoUrl' : string,
  'fontFamily' : string,
  'secondaryColor' : string,
  'brandName' : string,
  'textColor' : string,
}
export interface Patient {
  'dob' : string,
  'relationship' : string,
  'patientId' : bigint,
  'name' : string,
  'createdAt' : Time,
  'emergencyContact' : string,
  'isPrimary' : boolean,
  'bloodGroup' : string,
  'gender' : string,
  'customerId' : bigint,
  'chronicConditions' : Array<string>,
}
export interface PrescriptionLead {
  'id' : bigint,
  'file' : ExternalBlob,
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'phone' : string,
}
export interface SampleCollection {
  'id' : bigint,
  'status' : string,
  'scheduledTime' : bigint,
  'testNames' : Array<string>,
  'address' : string,
  'patientName' : string,
}
export interface SanitizedUserProfile {
  'name' : string,
  'role' : HealthcareRole,
  'isActive' : boolean,
}
export interface Service {
  'id' : bigint,
  'metaDescription' : string,
  'subcategory' : Subcategory,
  'name' : string,
  'description' : string,
  'isActive' : boolean,
  'targetAudience' : string,
  'serviceIntro' : string,
  'seoKeywords' : Array<string>,
  'metaTitle' : string,
  'category' : Category,
  'benefits' : string,
  'servicesIncluded' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Subcategory = { 'motherChildCare' : null } |
  { 'vaccination' : null } |
  { 'wellnessLifestyle' : null } |
  { 'healthCheckups' : null } |
  { 'caregiverServices' : null } |
  { 'icuSetup' : null } |
  { 'b2bServices' : null } |
  { 'nursingCare' : null } |
  { 'doctorConsultation' : null } |
  { 'specialistCare' : null } |
  { 'equipmentRental' : null } |
  { 'labTests' : null } |
  { 'physiotherapy' : null } |
  { 'corporateHealth' : null } |
  { 'diagnostics' : null } |
  { 'medicineDelivery' : null };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'principal' : string,
  'documents' : Array<string>,
  'bookedTimes' : Array<BookedTime>,
  'bookedServices' : Array<bigint>,
  'name' : string,
  'role' : HealthcareRole,
  'insuranceDetails' : string,
  'isActive' : boolean,
  'email' : string,
  'locationHistory' : Array<string>,
  'phone' : string,
  'sharedProfile' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vital {
  'reading' : string,
  'status' : string,
  'vitalId' : bigint,
  'patientId' : bigint,
  'type' : string,
  'unit' : string,
  'timestamp' : Time,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addBooking' : ActorMethod<
    [
      string,
      string,
      bigint,
      { 'whatsapp' : { 'phoneNumber' : string } } |
        { 'callBack' : { 'requestedTime' : bigint } } |
        { 'scheduledVisit' : { 'timestamp' : bigint } },
      {
        'subcategory' : Subcategory,
        'description' : string,
        'preferredDate' : [] | [bigint],
        'preferredTime' : [] | [bigint],
        'category' : Category,
        'urgent' : boolean,
      },
    ],
    { 'bookingId' : bigint, 'message' : string }
  >,
  'addCustomer' : ActorMethod<
    [string, string, string, string, [] | [Principal]],
    bigint
  >,
  'addDoctorAppointment' : ActorMethod<
    [bigint, bigint, bigint, Time, string, string, number, string],
    bigint
  >,
  'addDoctorProfile' : ActorMethod<
    [
      bigint,
      string,
      Array<string>,
      bigint,
      number,
      string,
      string,
      Array<string>,
      number,
      bigint,
      string,
    ],
    bigint
  >,
  'addHealthPackage' : ActorMethod<
    [
      string,
      string,
      string,
      Array<string>,
      number,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'addPatient' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      boolean,
    ],
    bigint
  >,
  'addSeoData' : ActorMethod<
    [string, string, Array<string>, string, string, string, string],
    bigint
  >,
  'addService' : ActorMethod<
    [
      string,
      Category,
      Subcategory,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
    ],
    bigint
  >,
  'addVital' : ActorMethod<[bigint, string, string, string, string], bigint>,
  'allServices' : ActorMethod<[], Array<Service>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignHealthcareRole' : ActorMethod<[Principal, HealthcareRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteConsultationNote' : ActorMethod<[bigint], undefined>,
  'deleteCustomer' : ActorMethod<[bigint], undefined>,
  'deleteDoctorAppointment' : ActorMethod<[bigint], undefined>,
  'deleteDoctorEarning' : ActorMethod<[bigint], undefined>,
  'deleteDoctorProfile' : ActorMethod<[bigint], undefined>,
  'deleteHealthPackage' : ActorMethod<[bigint], undefined>,
  'deletePatient' : ActorMethod<[bigint], undefined>,
  'deleteSeoData' : ActorMethod<[bigint], undefined>,
  'deleteService' : ActorMethod<[bigint], undefined>,
  'deleteVital' : ActorMethod<[bigint], undefined>,
  'getActiveDiagnosticTests' : ActorMethod<[], Array<DiagnosticTest>>,
  'getActiveHealthPackages' : ActorMethod<[], Array<HealthPackage>>,
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllDiagnosticTests' : ActorMethod<[], Array<DiagnosticTest>>,
  'getAllDoctors' : ActorMethod<[], Array<DoctorProfile>>,
  'getAllHealthPackages' : ActorMethod<[], Array<HealthPackage>>,
  'getAllPatients' : ActorMethod<[], Array<Patient>>,
  'getAllPrescriptionLeads' : ActorMethod<[], Array<PrescriptionLead>>,
  'getAllSeoData' : ActorMethod<[], Array<Data>>,
  'getAllVitals' : ActorMethod<[], Array<Vital>>,
  'getBookingById' : ActorMethod<[bigint], [] | [Booking]>,
  'getBookingsByUserProfile' : ActorMethod<
    [Principal, HealthcareRole],
    Array<Booking>
  >,
  'getBrandInfo' : ActorMethod<[], Info__1>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConsultationNotesByAppointment' : ActorMethod<
    [bigint],
    [] | [ConsultationNote]
  >,
  'getContactInfo' : ActorMethod<[], [] | [Info]>,
  'getCustomerById' : ActorMethod<[bigint], [] | [Customer]>,
  'getDiagnosticTestById' : ActorMethod<[bigint], [] | [DiagnosticTest]>,
  'getDiagnosticTestCategories' : ActorMethod<[], Array<string>>,
  'getDiagnosticTestSampleTypes' : ActorMethod<[], Array<string>>,
  'getDiagnosticTestsByCategory' : ActorMethod<[string], Array<DiagnosticTest>>,
  'getDiagnosticTestsByPriceRange' : ActorMethod<
    [number, number],
    Array<DiagnosticTest>
  >,
  'getDiagnosticTestsBySampleType' : ActorMethod<
    [string],
    Array<DiagnosticTest>
  >,
  'getDoctorById' : ActorMethod<[bigint], [] | [DoctorProfile]>,
  'getDoctorDashboardData' : ActorMethod<[bigint], [] | [DoctorDashboardStats]>,
  'getDoctorEarnings' : ActorMethod<[bigint], Array<DoctorEarning>>,
  'getDoctorProfilesByCategory' : ActorMethod<[string], Array<DoctorProfile>>,
  'getDoctorProfilesBySpecialization' : ActorMethod<
    [string],
    Array<DoctorProfile>
  >,
  'getHealthPackageById' : ActorMethod<[bigint], [] | [HealthPackage]>,
  'getHealthPackageCategories' : ActorMethod<[], Array<string>>,
  'getHealthPackagesByCategory' : ActorMethod<[string], Array<HealthPackage>>,
  'getHealthPackagesByPriceRange' : ActorMethod<
    [number, number],
    Array<HealthPackage>
  >,
  'getHealthPackagesBySampleType' : ActorMethod<[string], Array<HealthPackage>>,
  'getMyCustomerProfile' : ActorMethod<[], [] | [Customer]>,
  'getMyFamilyVitals' : ActorMethod<[], Array<Vital>>,
  'getMyPatients' : ActorMethod<[], Array<Patient>>,
  'getPatientById' : ActorMethod<[bigint], [] | [Patient]>,
  'getPatientsByCustomerId' : ActorMethod<[bigint], Array<Patient>>,
  'getPrescriptionLead' : ActorMethod<[bigint], [] | [PrescriptionLead]>,
  'getServiceIcons' : ActorMethod<[], Array<[string, string]>>,
  'getServicesByCategory' : ActorMethod<[Category], Array<Service>>,
  'getServicesBySubcategory' : ActorMethod<[Subcategory], Array<Service>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserRoleByPrincipal' : ActorMethod<[Principal], HealthcareRole>,
  'getVitalById' : ActorMethod<[bigint], [] | [Vital]>,
  'getVitalsByPatientId' : ActorMethod<[bigint], Array<Vital>>,
  'hasLabExecutiveCapabilities' : ActorMethod<[Principal], boolean>,
  'hasPhlebotomistRole' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<[Principal, UserProfile]>>,
  'listDoctorAppointments' : ActorMethod<[bigint], Array<DoctorAppointment>>,
  'listServicesByCategory' : ActorMethod<[Category], Array<Service>>,
  'logout' : ActorMethod<[], undefined>,
  'previewGetAllBookings' : ActorMethod<[], Array<Booking>>,
  'previewGetAllServices' : ActorMethod<[], Array<Service>>,
  'previewGetAllUsers' : ActorMethod<[], Array<SanitizedUserProfile>>,
  'previewGetDashboardStats' : ActorMethod<[], DashboardStats>,
  'previewGetMockUsers' : ActorMethod<[], Array<SanitizedUserProfile>>,
  'previewGetSampleCollections' : ActorMethod<[], Array<SampleCollection>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveConsultationNote' : ActorMethod<
    [bigint, bigint, bigint, string, string, Time, Array<string>],
    bigint
  >,
  'searchDiagnosticTests' : ActorMethod<[string], Array<DiagnosticTest>>,
  'searchServicesByKeyword' : ActorMethod<[string], Array<Service>>,
  'setBrandInfo' : ActorMethod<
    [string, string, string, string, string, string, string],
    undefined
  >,
  'setContactInfo' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'setUserActiveStatus' : ActorMethod<[Principal, boolean], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateConsultationNote' : ActorMethod<[bigint, ConsultationNote], undefined>,
  'updateCustomer' : ActorMethod<
    [bigint, string, string, string, string, number, bigint, string],
    undefined
  >,
  'updateDoctorAppointment' : ActorMethod<
    [bigint, DoctorAppointment],
    undefined
  >,
  'updateDoctorEarning' : ActorMethod<[bigint, DoctorEarning], undefined>,
  'updateDoctorProfile' : ActorMethod<[bigint, DoctorProfile], undefined>,
  'updateHealthPackage' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      Array<string>,
      number,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updatePatient' : ActorMethod<
    [
      bigint,
      bigint,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      boolean,
    ],
    undefined
  >,
  'updateSeoData' : ActorMethod<
    [bigint, string, string, Array<string>, string, string, string, string],
    undefined
  >,
  'updateService' : ActorMethod<
    [
      bigint,
      string,
      Category,
      Subcategory,
      string,
      string,
      string,
      string,
      string,
      Array<string>,
      string,
      string,
    ],
    undefined
  >,
  'updateVital' : ActorMethod<
    [bigint, bigint, string, string, string, string],
    undefined
  >,
  'uploadPrescription' : ActorMethod<
    [string, string, string, ExternalBlob],
    bigint
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];